#!/bin/sh
# it seems that the module exe the exec script at the same time as the on-click event
sleep 0.01
if [ "$(dunstctl is-paused)" = "true" ]; then
	printf "\ndisbled\ndisabled"
else
	printf "\nenabled\nenabled"
fi
