#! /bin/sh
if [ "$1" -eq 3 ]; 
then
	dunstctl history-pop
elif [ "$1" -eq 1 ]; 
then
	dunstctl set-paused toggle
fi
if [ $(dunstctl is-paused) = "true" ];
then
	echo "󰂛"
	echo
	echo \#f7768e
else
	echo "󰂚"
fi
