#!/bin/sh

target=""
[ -z "$1" ] && read -r target
[ -z "$target" ] && target="$1"

dirs=$(find -L "$target" -mindepth 1 -type d)
mkdir -p "$XDG_CONFIG_HOME"/cmus/playlists/
echo "$dirs" | while read -r dir; do
	splice="$(echo "$dir" | sed 's#.*/##')"
	dest="$XDG_CONFIG_HOME"/cmus/playlists/"$splice"
	find "$dir" -maxdepth 1 -type f >"$dest"
done
