#!/bin/sh

#TODO: choose if if the user wants to include the to level dir or not
#TODO: accepts the file from stdin

dirs=$(find -L "$1" -maxdepth 1 -mindepth 1 -type d)
# dirs=$(find -L "$1" -maxdepth 1 -type d)
mkdir -p "$XDG_CONFIG_HOME"/cmus/playlists/
echo "$dirs" | while read -r dir; do
	splice="$(echo "$dir" | sed 's#.*/##')"
	dest="$XDG_CONFIG_HOME"/cmus/playlists/"$splice"
	find "$dir" -maxdepth 1 -type f >"$dest"
done
