#!/bin/zsh
alias virc='nvim ~/.config/nvim/init.lua' 
alias zshrc='nvim ~/.config/zsh/.zshrc'
alias i3rc='nvim ~/.config/i3/config' 
alias kittyrc='nvim ~/.config/kitty/kitty.conf'
alias xprc='nvim ~/.xprofile'
alias dfrc='nvim ~/dotfiles'

#Neovim for Godot 
alias vig='nvim --listen /tmp/godothost.pipe'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias rg='rg --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i -v"
alias mv='mv -i -v'
# alias rm='trash-put -f -v'
alias xdg-open='mimeo'

# ls colors
alias ls='lsd'
alias ls.='lsd -a'
alias lsl='lsd -l'
alias lsl.='lsd -l -a'

# mkdir recursiv by default
alias mkdir='mkdir -v -p'

alias lf='lfcd'

# git 
alias lg='lazygit'
alias gst='git status'
alias gal='git add .'
alias ga='git add'
alias grs='git restore --staged'
alias grsa='git restore --staged .'
alias gct='git commit'
alias gps='git push'
alias gpso='git push origin'
alias gpl='git pull'
alias gplo='git pull origin'
alias gd='git diff'
alias gcl='git clone'
alias gco='git checkout'
alias gbr='git branch'

gcth(){
	git log --oneline --color | fzf --multi --ansi --preview 'git show --color {+1} | diff-so-fancy' --bind 'enter:execute(git diff {+1}~ {+1})'
}

#yt-dlp usage
alias ydl='yt-dlp'
alias ydla='yt-dlp -f 251'
alias ydlF='yt-dlp -F'
alias ydlf='yt-dlp -f'
alias ydl720='yt-dlp -f 247+250'
alias vi='nvim'
alias nsxiv='nsxiv -a'

#Mpv
alias mpv4='mpv --profile=480p --really-quiet --no-terminal'
alias mpv7='mpv --profile=720p --really-quiet --no-terminal'
alias mpv18='mpv --profile=1080p --really-quiet --no-terminal'
alias mpva='mpv --profile=a'

#fzf usages
fdrc(){
	fd -t $1 --color=always | fzf --ansi
}

pcd(){
	cd "$(fdrc d)"
}

open(){
	getpt f | xargs mimeo
}

cppt(){
	fdrc $1 |  tr -d '\n' | xclip -selection c
}

getpt(){
	fdrc $1 | sed 's/^/"/;s/$/"/' | tr -d '\n'
}

#paru stuff
alias pacin='paru -S'
#delelte all orphans
alias pacdo='paru -Qtdq | paru -Rns -'

#show installed packages and sort them by installed date 
pacsd(){
	expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n "$1"
}

#Show all installed packages 
pacsa(){
	paru -Qq | fzf --preview 'paru -Qil {}' --layout=reverse --bind 'enter:execute(paru -Qil {} | less)'
}

pacei(){
	paru -Qetq | fzf --preview 'paru -Qil {}' --layout=reverse --bind 'enter:execute(paru -Qil {} | bat -n)'
}

#use paru to make package explicitly installed
alias pacme='paru -S --asexplicit'

# For when keys break
alias pacman-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

#replace default programmes with better ones that have diffrent way of use
alias rename='perl-rename'

alias aria='aria2c --check-integrity=true'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

# LFcd
lfcd(){
    tmp="$(mktemp)"
    lfu -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}
