#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='cd ~/.config/nvim/ && nvim .'
alias zshrc='cd ~/.config/zsh/ && nvim .'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i -v"
alias mv='mv -i -v'
alias rm='rm -r -v'

# ls colors
alias ls='ls --color=auto'
alias l.='ls --color=auto -a'
alias lsl='ls --color=auto -l'
alias lsl.='ls --color=auto -l -a'

# mkdir recursiv by default
alias mkdir='mkdir -v -p'

# git 
alias gst='git status'
alias gal='git add .'
alias ga='git add'
alias gct='git commit'
alias gpso='git push origin'
alias gplo='git pull origin'
alias gd='git diff'
alias gcl='git clone'

#youtube-dl
alias ydl='youtube-dl'
alias ydlb='youtube-dl -f best'
alias ydlF='youtube-dl -F'
alias ydlf='youtube-dl -f'

#Neovim for Godot 
alias nvimg='nvim --listen godothost .'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"
