#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias vimrc='cd ~/.config/nvim/ && nvim .'
alias zshrc='cd ~/.config/zsh/ && nvim .'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i -v"
alias mv='mv -i -v'
alias rm='rm -r -v'

# ls colors
alias ls='ls --color=auto -h'
alias l.='ls --color=auto -a -h'
alias lsl='ls --color=auto -l -h'
alias lsl.='ls --color=auto -l -a -h'

# mkdir recursiv by default
alias mkdir='mkdir -v -p'

# git 
alias gst='git status'
alias gal='git add .'
alias ga='git add'
alias gct='git commit'
alias gps='git push'
alias gpso='git push origin'
alias gpl='git pull'
alias gplo='git pull origin'
alias gd='git diff'
alias gcl='git clone'
alias gco='git checkout'
alias gbr='git branch'

#yt-dlp usage
alias ydl='yt-dlp'
alias ydla='yt-dlp -f 251'
alias ydlF='yt-dlp -F'
alias ydlf='yt-dlp -f'

alias vim='nvim'

#Neovim for Godot 
alias vimg='nvim --listen godothost .'

#fzf usages
pcd(){
	cd "$(find -type d | fzf)"
}

open(){
	getpath f | xargs -0 -I arg sh -c "nohup xdg-open arg &"
}

copypath(){
	find -type "$1" | fzf | sed "s/^../'/;s/$/'/" | tr -d '\n' | xclip -selection c
}

getpath(){
	find -type "$1" | fzf | sed "s/^../'/;s/$/'/" | tr -d '\n'
}

#Pacman and yay stuff
alias pacin='sudo pacman -S'
alias yayin='yay -S'
alias pacdo='yay -Qtdq | yay -Rns -'

pacsd(){
	expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n "$1"
}

yaysa(){
	yay -Qq | fzf --preview 'yay -Qil {}' --layout=reverse --bind 'enter:execute(yay -Qil {} | less)'
}

pacsa(){
	sudo pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
}

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"
