#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias vimrc='cd ~/.config/nvim/ && nvim .'
alias zshrc='cd ~/.config/zsh/ && nvim .'
alias i3rc='cd ~/.config/i3 && nvim .'
alias kittyrc='cd ~/.config/kitty/ && nvim .'
alias xprc='nvim ~/.xprofile'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i -v"
alias mv='mv -i -v'
alias rm='trash-put -f -v'

# ls colors
alias ls='ls --color=auto -h'
alias l.='ls --color=auto -a -h'
alias lsl='ls --color=auto -l -h'
alias lsl.='ls --color=auto -l -a -h'

# mkdir recursiv by default
alias mkdir='mkdir -v -p'

# git 
alias gst='git status'
alias gal='git add .'
alias ga='git add'
alias grs='git restore --staged'
alias gct='git commit'
alias gps='git push'
alias gpso='git push origin'
alias gpl='git pull'
alias gplo='git pull origin'
alias gd='git diff'
alias gcl='git clone'
alias gco='git checkout'
alias gbr='git branch'
alias gcth="git log --oneline --color | fzf --multi --ansi --preview 'git show --color {+1}'"

#yt-dlp usage
alias ydl='yt-dlp'
alias ydla='yt-dlp -f 251'
alias ydlF='yt-dlp -F'
alias ydlf='yt-dlp -f'

alias vim='nvim'
alias nsxiv='nsxiv -a'
#Neovim for Godot 
alias vimg='nvim --listen godothost .'

#fzf usages
pcd(){
	cd "$(fd -t d -HI --exclude .git -E Homework -E .cashe | fzf)"
}

open(){
	getpt f | xargs -0 -I arg sh -c "nohup mimeo arg &"
}

cppt(){
	fd -t "$1" -HI --exclude .cache -E Homework --exclude .npm/_cacache/ --exclude .git --color=always | fzf --ansi |  tr -d '\n' | xclip -selection c
}

getpt(){
	fd -t "$1" -HI --exclude .cache -E Homework --exclude .npm/_cacache/ --exclude .git --color=always | fzf --ansi | sed 's/^/"/;s/$/"/' | tr -d '\n'
}

openh(){
	fd . '/home/arrowx/File/Homework/H-Manga' -t d | fzf --preview-window wrap --preview 'kitty icat --transfer-mode file --clear ; kitty icat --place $FZF_PREVIEW_COLUMNS"x"$FZF_PREVIEW_LINES@$(expr $FZF_PREVIEW_COLUMNS + 6)x1 --transfer-mode file {}/$(ls {} | head -n1)' | xargs -I arg nsxiv 'arg' 
}

#yay stuff
alias pacin='yay -S'
#delelte all orphans
alias pacdo='yay -Qtdq | yay -Rns -'

#show installed packages and sort them by installed date 
pacsd(){
	expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n "$1"
}

#Show all installed packages 
pacsa(){
	yay -Qq | fzf --preview 'yay -Qil {}' --layout=reverse --bind 'enter:execute(yay -Qil {} | less)'
}

alias monrest='xrandr --output LVDS-1 --mode 1400x900'
alias monorig='xrandr --output LVDS-1 --mode 1600x900'
#use yay to make package explicitly installed
alias pacme='yay -S --asexplicit'

# For when keys break
alias archlinx-fix-keys="doas pacman-key --init && doas pacman-key --populate archlinux && doas pacman-key --refresh-keys"

trackpad(){
	xinput set-prop 14 "Device Enabled" $1
}

#replace default programmes with better ones that have diffrent way of use
alias rename='perl-rename'

alias aria='aria2c --check-integrity=true'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias anime='ani-cli -q 720'
